// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/systeminfo.proto

package recordMySystem_grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SystemInfoReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HostName             string   `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	CpuPercentage        float32  `protobuf:"fixed32,3,opt,name=cpuPercentage,proto3" json:"cpuPercentage,omitempty"`
	MemoryUsage          float32  `protobuf:"fixed32,4,opt,name=memoryUsage,proto3" json:"memoryUsage,omitempty"`
	Temperature          float32  `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	BatteryPercentage    float32  `protobuf:"fixed32,6,opt,name=batteryPercentage,proto3" json:"batteryPercentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemInfoReq) Reset()         { *m = SystemInfoReq{} }
func (m *SystemInfoReq) String() string { return proto.CompactTextString(m) }
func (*SystemInfoReq) ProtoMessage()    {}
func (*SystemInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_96bc51616fb440c3, []int{0}
}

func (m *SystemInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfoReq.Unmarshal(m, b)
}
func (m *SystemInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfoReq.Marshal(b, m, deterministic)
}
func (m *SystemInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfoReq.Merge(m, src)
}
func (m *SystemInfoReq) XXX_Size() int {
	return xxx_messageInfo_SystemInfoReq.Size(m)
}
func (m *SystemInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfoReq proto.InternalMessageInfo

func (m *SystemInfoReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SystemInfoReq) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *SystemInfoReq) GetCpuPercentage() float32 {
	if m != nil {
		return m.CpuPercentage
	}
	return 0
}

func (m *SystemInfoReq) GetMemoryUsage() float32 {
	if m != nil {
		return m.MemoryUsage
	}
	return 0
}

func (m *SystemInfoReq) GetTemperature() float32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *SystemInfoReq) GetBatteryPercentage() float32 {
	if m != nil {
		return m.BatteryPercentage
	}
	return 0
}

type SystemInfoRes struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemInfoRes) Reset()         { *m = SystemInfoRes{} }
func (m *SystemInfoRes) String() string { return proto.CompactTextString(m) }
func (*SystemInfoRes) ProtoMessage()    {}
func (*SystemInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_96bc51616fb440c3, []int{1}
}

func (m *SystemInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfoRes.Unmarshal(m, b)
}
func (m *SystemInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfoRes.Marshal(b, m, deterministic)
}
func (m *SystemInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfoRes.Merge(m, src)
}
func (m *SystemInfoRes) XXX_Size() int {
	return xxx_messageInfo_SystemInfoRes.Size(m)
}
func (m *SystemInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfoRes proto.InternalMessageInfo

func (m *SystemInfoRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SystemInfoReq)(nil), "recordMySystem_grpc.SystemInfoReq")
	proto.RegisterType((*SystemInfoRes)(nil), "recordMySystem_grpc.SystemInfoRes")
}

func init() {
	proto.RegisterFile("proto/systeminfo.proto", fileDescriptor_96bc51616fb440c3)
}

var fileDescriptor_96bc51616fb440c3 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xb1, 0x4a, 0xc4, 0x40,
	0x10, 0x86, 0xdd, 0xe8, 0x9d, 0x3a, 0x72, 0x07, 0x8e, 0x28, 0xcb, 0x55, 0x21, 0x58, 0x44, 0xd0,
	0x08, 0xfa, 0x06, 0x76, 0x16, 0x8a, 0x24, 0xd8, 0xd8, 0x48, 0x2e, 0x99, 0x3b, 0x53, 0x6c, 0x36,
	0xce, 0x4e, 0x8a, 0x3c, 0xa7, 0x2f, 0x24, 0xd9, 0xa0, 0x24, 0x2a, 0x58, 0xfe, 0xdf, 0x7c, 0x30,
	0xcc, 0x3f, 0x70, 0xd6, 0xb0, 0x15, 0x7b, 0xed, 0x3a, 0x27, 0x64, 0xaa, 0x7a, 0x63, 0x13, 0x0f,
	0xf0, 0x84, 0xa9, 0xb0, 0x5c, 0x3e, 0x74, 0x99, 0x9f, 0xbc, 0x6e, 0xb9, 0x29, 0xa2, 0x0f, 0x05,
	0x8b, 0x21, 0xdf, 0xd7, 0x1b, 0x9b, 0xd2, 0x3b, 0x2e, 0x21, 0xa8, 0x4a, 0xad, 0x42, 0x15, 0x1f,
	0xa6, 0x41, 0x55, 0xe2, 0x0a, 0x0e, 0xde, 0xac, 0x93, 0xc7, 0xdc, 0x90, 0x0e, 0x3c, 0xfd, 0xce,
	0x78, 0x0e, 0x8b, 0xa2, 0x69, 0x9f, 0x88, 0x0b, 0xaa, 0x25, 0xdf, 0x92, 0xde, 0x0d, 0x55, 0x1c,
	0xa4, 0x53, 0x88, 0x21, 0x1c, 0x19, 0x32, 0x96, 0xbb, 0x67, 0xd7, 0x3b, 0x7b, 0xde, 0x19, 0xa3,
	0xde, 0x10, 0x32, 0x0d, 0x71, 0x2e, 0x2d, 0x93, 0x9e, 0x0d, 0xc6, 0x08, 0xe1, 0x25, 0x1c, 0xaf,
	0x73, 0x11, 0xe2, 0x6e, 0xb4, 0x6d, 0xee, 0xbd, 0xdf, 0x83, 0xe8, 0x62, 0x7a, 0x94, 0x43, 0x0d,
	0xfb, 0x86, 0x9c, 0x5f, 0x3f, 0x5c, 0xf6, 0x15, 0x6f, 0x08, 0x96, 0xe9, 0xa4, 0x17, 0xcc, 0x60,
	0x96, 0x89, 0x65, 0xc2, 0x28, 0xf9, 0xa3, 0xb1, 0x64, 0xd2, 0xd6, 0xea, 0x7f, 0xc7, 0x45, 0x3b,
	0xb1, 0xba, 0x3b, 0x7d, 0xf9, 0x51, 0xff, 0x55, 0x2f, 0xae, 0xe7, 0xfe, 0x35, 0xb7, 0x9f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xa6, 0x08, 0x46, 0x42, 0xb4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RecordMySystemClient is the client API for RecordMySystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecordMySystemClient interface {
	Store(ctx context.Context, opts ...grpc.CallOption) (RecordMySystem_StoreClient, error)
}

type recordMySystemClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordMySystemClient(cc grpc.ClientConnInterface) RecordMySystemClient {
	return &recordMySystemClient{cc}
}

func (c *recordMySystemClient) Store(ctx context.Context, opts ...grpc.CallOption) (RecordMySystem_StoreClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RecordMySystem_serviceDesc.Streams[0], "/recordMySystem_grpc.RecordMySystem/Store", opts...)
	if err != nil {
		return nil, err
	}
	x := &recordMySystemStoreClient{stream}
	return x, nil
}

type RecordMySystem_StoreClient interface {
	Send(*SystemInfoReq) error
	CloseAndRecv() (*SystemInfoRes, error)
	grpc.ClientStream
}

type recordMySystemStoreClient struct {
	grpc.ClientStream
}

func (x *recordMySystemStoreClient) Send(m *SystemInfoReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *recordMySystemStoreClient) CloseAndRecv() (*SystemInfoRes, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SystemInfoRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RecordMySystemServer is the server API for RecordMySystem service.
type RecordMySystemServer interface {
	Store(RecordMySystem_StoreServer) error
}

// UnimplementedRecordMySystemServer can be embedded to have forward compatible implementations.
type UnimplementedRecordMySystemServer struct {
}

func (*UnimplementedRecordMySystemServer) Store(srv RecordMySystem_StoreServer) error {
	return status.Errorf(codes.Unimplemented, "method Store not implemented")
}

func RegisterRecordMySystemServer(s *grpc.Server, srv RecordMySystemServer) {
	s.RegisterService(&_RecordMySystem_serviceDesc, srv)
}

func _RecordMySystem_Store_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RecordMySystemServer).Store(&recordMySystemStoreServer{stream})
}

type RecordMySystem_StoreServer interface {
	SendAndClose(*SystemInfoRes) error
	Recv() (*SystemInfoReq, error)
	grpc.ServerStream
}

type recordMySystemStoreServer struct {
	grpc.ServerStream
}

func (x *recordMySystemStoreServer) SendAndClose(m *SystemInfoRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *recordMySystemStoreServer) Recv() (*SystemInfoReq, error) {
	m := new(SystemInfoReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RecordMySystem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recordMySystem_grpc.RecordMySystem",
	HandlerType: (*RecordMySystemServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Store",
			Handler:       _RecordMySystem_Store_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/systeminfo.proto",
}
